### ISSUE TITLE
Uncaught TypeError: img.toPng is not a function

### ISSUE THREAD

**Issue by otanao1** [csbun/atom-markclip#10]
[Enter steps to reproduce:]

1. Hi! Paste Picture from Clipbord (screenShot) . TypeError is happen
2. Setting: SaveType is ``file in folder``
3. my atom version is highest(1.28.0)

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [markclip](https://github.com/csbun/atom-markclip) package 0.4.0

### Stack Trace

Uncaught TypeError: img.toPng is not a function

```
At /Users/nornorthpoint77/.atom/packages/markclip/lib/markclip.coffee:75

TypeError: img.toPng is not a function
    at Object.handleInsertEvent (/packages/markclip/lib/markclip.coffee:75:41)
    at /packages/markclip/lib/markclip.coffee:99:34)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -8:39.2.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
  3x -5:03.1.0 core:cancel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:10.8.0 markclip:insert (input.hidden-input)
     -2:58.9.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:01.8.0 markclip:insert (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.4 
atom-csv-markdown 1.0.2 
atom-runner 2.7.1 
atomic-emacs 0.12.1 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
browser-plus 0.0.98 
busy-signal 1.4.3 
convert-to-utf8 0.2.4 
date 2.1.0 
document-outline 2.0.1 
ex-mode 0.18.0 
file-icons 2.1.16 
git-plus 7.10.2 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
japanese-menu 1.14.0 
japanese-word-selection 0.5.1 
language-powershell 4.0.1 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
markclip 0.4.0 
markdown-pdf 2.2.0 
markdown-preview-plus 3.3.0 
markdown-table-editor 1.0.2 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
minimap 4.29.8 
project-manager 3.3.5 
python-indent 1.1.4 
show-ideographic-space 1.0.2 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.4 
tidy-markdown 3.0.1 
tool-bar 1.1.4 
tool-bar-markdown-writer 0.3.1 
vim-mode-plus 1.27.0 
wordcount 2.10.4 
```

**Comment by otanao1** [comment]
i found it! 

deprecated ``NativeImage.toPng``  in electron 2.0.
 FIX ``toPng -> toPNG`` two-line fix

https://github.com/electron/electron/issues/13169

**Comment by alejandrocq** [comment]
@otanao1 I have created a PR with your solution ;) https://github.com/csbun/atom-markclip/pull/11

**Comment by csbun** [comment]
try [0.5.5](https://github.com/csbun/atom-markclip/releases/tag/v0.5.5)

**Comment by csbun** [comment]
Thanks @alejandrocq and @avonmoll
