### ISSUE TITLE
Uncaught TypeError: img.toDataUrl is not a function

### ISSUE THREAD

**Issue by imagepit** [csbun/atom-markclip#4]
Uncaught TypeError is occurred when I paste image in markdown file.

![](https://www.evernote.com/l/AB0T4SendbRGG7tK4coahKr0Wh9aJHzGCbUB/image.png)

Environments is below.

- Mac OS 10.12(Sierra)
- Atom 1.12.3
- markclip 0.2.3

Stack trace is below.

```
TypeError: img.toDataUrl is not a function
    at Object.handleCtrlVEvent (/Users/imagepit/.atom/packages/markclip/lib/markclip.coffee:60:51)
    at /Users/imagepit/.atom/packages/markclip/lib/markclip.coffee:77:10
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:125:28)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:389:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

Please help me.

**Comment by csbun** [comment]
fix! [v0.2.4](https://github.com/csbun/atom-markclip/releases/tag/v0.2.4)
